adam_epsilon: 1.0e-08
attention_dropout: null
cache_dir: ''
check_val_every_n_epoch: 1
ckpt_metric: val-ROUGE-1
ckpt_mode: max
ckpt_name: !!python/object/apply:pathlib.PosixPath
- /
- workspace
- GAR
- checkpointepoch=XXX.ckpt
config_name: ''
data_dir: /scratch/kshenoy/data/nq-sentence/
decoder_layerdrop: null
do_predict: true
do_train: true
dropout: null
encoder_layerdrop: null
eval_batch_size: 256
fp16: false
fp16_opt_level: O1
freeze_decoder: false
freeze_embeds: false
freeze_encoder: false
gpus: 1
gradient_accumulation_steps: 1
label_decay: 1
label_smoothing: 0.0
learning_rate: 3.0e-05
limit_val_batches: 1.0
load_ckpt_name: null
local_rank: -1
logger_name: default
max_grad_norm: 1.0
max_source_length: 20
max_target_length: 64
min_gpu_memory: 13000
mode_real: seq2seq
model_name_or_path: facebook/bart-large
n_gpu: 1
n_tpu_cores: 0
num_train_epochs: 100
output_dir: /scratch/kshenoy/output/GAR_models/nq-sentence/
remark: generator_train_nq_A
save_top_k: 1
seed: 42
tokenizer_name: ''
train_batch_size: 128
val_check_interval: 1.0
warmup_steps: 0
weight_decay: 0.0
